# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-14 08:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0003_ids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ids',
            name='identifier',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
