# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-15 18:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0004_auto_20181215_1829'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='profile_picture',
            new_name='pic',
        ),
    ]
