# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-14 09:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0005_auto_20181214_0851'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ids',
        ),
    ]
