# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-15 18:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0005_auto_20181215_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pic',
            field=models.ImageField(default='media/pics/profile.png', upload_to='pics'),
        ),
    ]
