# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-14 11:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0007_idss'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='comm',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
