# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-19 11:52
from __future__ import unicode_literals

from django.db import migrations
import pyuploadcare.dj.models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0009_auto_20181218_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_url',
            field=pyuploadcare.dj.models.ImageField(blank=True),
        ),
    ]
