# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-21 05:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0011_auto_20181219_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='name',
            field=models.CharField(blank=True, max_length=31),
        ),
    ]
